Repository foam-framework/foam2, pull requests merged in 2018-11, with the labels that each got.

#1628 Some tweaks around flow documents
  src/files.js
  src/foam/core/Slot.js
  src/foam/flow/Document.js
  src/foam/graphics/CView.js
  src/foam/u2/Element.js
Labels: cla: yes

#1649 DAO controller improvements
  src/files.js
  src/foam/comics/BrowserView.js
  src/foam/comics/DAOController.js
  src/foam/comics/DAOControllerView.js
  src/foam/comics/SearchMode.js
  src/foam/nanos/menu/DAOMenu.js
  src/foam/u2/search/TextSearchView.js
  src/foam/u2/view/ReciprocalSearch.js
  src/foam/u2/view/SimpleSearch.js
  tools/classes.js
Labels: cla: yes, enhancement

#1640 Avoid launching the same side menu item contents
  src/foam/nanos/doc/DocumentationView.js
  src/foam/nanos/menu/DocumentFileMenu.js
  src/foam/nanos/u2/navigation/SideNavigationItemView.js
Labels: cla: yes

#1648 Adding code snippet views for SELECT, PUT and DELETE
  src/files.js
  src/foam/doc/CodeTabs.js
  src/foam/doc/DigDeleteView.js
  src/foam/doc/DigPutView.js
  src/foam/doc/DigSelectView.js
  src/foam/u2/Tabs.js
  src/foam/u2/UnstyledTabs.js
Labels: cla: yes

#1652 Early ChartJS Components+Demos
  src/org/chartjs/Bar.js
  src/org/chartjs/Lib.js
  src/org/chartjs/Line.js
  src/org/chartjs/Pie.js
  src/org/chartjs/demos/Pie.js
  src/org/chartjs/demos/Stock.js
Labels: cla: yes

#1639 Add 'System' flag to User model
  src/foam/dao/tests.jrl
  src/foam/nanos/auth/AuthenticatedUserDAO.java
  src/foam/nanos/auth/AuthenticatedUserDAOTest.java
  src/foam/nanos/auth/User.js
Labels: cla: yes

#1654 improved navigation styling
  src/foam/nanos/u2/navigation/FooterView.js
  src/foam/nanos/u2/navigation/NavigationView.js
  src/foam/nanos/u2/navigation/SideNavigationItemView.js
Labels: cla: yes

#1655 Add keyup listener on passwordInput
  src/foam/u2/view/PasswordView.js
Labels: cla: yes

#1656 Add documentation for onPasswordKeyUp listener
  src/foam/u2/view/PasswordView.js
Labels: cla: yes

#1657 Remove listener function and bind data using onKey on input
  src/foam/u2/view/PasswordView.js
Labels: cla: yes

#1658 catching errors when running scripts/tests on the client
  src/foam/nanos/script/Script.js
  src/foam/nanos/test/Test.js
Labels: cla: yes

#1664 Enable toggle filters
  src/foam/comics/BrowserView.js
  src/foam/comics/DAOController.js
  src/foam/nanos/menu/DAOMenu.js
  src/foam/nanos/menu/TreeGraphAltView.js
  src/foam/nanos/nanos.js
  src/foam/u2/view/TreeView.js
Labels: cla: yes

#1661 Update countryDAO & regionDAO
  src/regions
  src/services
Labels: cla: yes

#1660 Rich choice view
  src/files.js
  src/foam/u2/view/RichChoiceView.js
Labels: cla: yes

#1668 ability configure crons based on seconds
  src/foam/nanos/cron/Cron.js
  src/foam/nanos/cron/CronScheduler.java
Labels: cla: yes

#1669 cron second config defaults to 0
  src/foam/nanos/cron/Cron.js
Labels: cla: yes

#1666 Side Navigatoin Improvements
  src/foam/nanos/u2/navigation/NavigationView.js
  src/foam/nanos/u2/navigation/SideNavigation.js
  src/foam/nanos/u2/navigation/SideNavigationItemView.js
Labels: cla: yes

#1670 Modelled javax.servlet.Servlet for usage on client
  src/foam/nanos/nanos.js
  src/foam/nanos/servlet/Servlet.js
  src/foam/nanos/servlet/ServletMapping.js
  src/foam/nanos/servlet/VirtualHostRoutingServlet.js
  tools/classes.js
Labels: cla: yes

#1667 Remove ChartConfig and add color properties to bar/pie charts that can be editted from the Card.
  src/foam/dashboard/model/Visualization.js
  src/foam/dashboard/view/Bar.js
  src/foam/dashboard/view/Card.js
  src/foam/dashboard/view/Pie.js
  src/org/chartjs/AbstractChart.js
  src/org/chartjs/Bar.js
  src/org/chartjs/ChartConfig.js
  src/org/chartjs/Pie.js
Labels: cla: yes

#1671 fix treevieew
  src/foam/u2/view/TreeView.js
Labels: cla: yes

#1672 Fix table selection highlight
  src/foam/nanos/controller/AppStyles.js
Labels: cla: yes

#1674 Made LogMessage detail view text area more readable
  src/foam/nanos/logger/LogMessage.js
Labels: cla: no

#1665 DAO controller changes
  src/foam/comics/BrowserView.js
  src/foam/comics/DAOController.js
  src/foam/comics/DAOControllerView.js
Labels: cla: yes

#1678 Add isDescendantOf method to Group model
  src/foam/nanos/auth/Group.js
Labels: cla: yes

#1677 Added color codes to Admin -> Logs based on severity of log.
  src/foam/nanos/logger/LogMessage.js
  src/foam/nanos/logger/LogsView.js
Labels: cla: no

#1681 Changed severity color log to css blocks. Changed Back to ScrollTabl…
  src/foam/nanos/logger/LogMessage.js
  src/foam/nanos/logger/LogsView.js
Labels: cla: yes

#1673 F/np 3149/dig authentification
  src/foam/nanos/http/HttpParametersWebAgent.java
Labels: cla: yes

#1676 Refactor Email service interface
  src/foam/nanos/auth/Group.js
  src/foam/nanos/auth/email/EmailDocService.js
  src/foam/nanos/auth/email/EmailTokenService.js
  src/foam/nanos/auth/resetPassword/ResetPasswordTokenService.js
  src/foam/nanos/dig/DigWebAgent.java
  src/foam/nanos/notification/SendEmailNotificationDAO.java
  src/foam/nanos/notification/email/DAOEmailService.js
  src/foam/nanos/notification/email/EmailMessage.js
  src/foam/nanos/notification/email/EmailService.js
  src/foam/nanos/notification/email/SMTPEmailMessageDAO.js
  src/foam/nanos/notification/email/SMTPEmailService.js
Labels: cla: yes

#1684 Added additional check to ensure inner.sub exists
  src/foam/core/types.js
Labels: cla: yes

#1685 Made all properties read only and a few ui changes
  src/foam/nanos/logger/LogMessage.js
Labels: cla: yes

#1686 Disable newly added initObject, it's breaking Relationships
  src/foam/core/types.js
Labels: cla: yes

#1687 Add the sign in view property to the reset password view
  src/foam/nanos/auth/resetPassword/EmailView.js
Labels: cla: yes

#1688 fix dao create controller
  src/foam/comics/DAOCreateControllerView.js
Labels: cla: yes

#1689 Style changes
  src/foam/comics/DAOControllerView.js
  src/foam/nanos/controller/ApplicationController.js
Labels: cla: yes

#1682 TreeView and TableView styling
  src/foam/comics/DAOControllerView.js
  src/foam/nanos/controller/AppStyles.js
  src/foam/u2/view/TableView.js
  src/foam/u2/view/TreeView.js
Labels: cla: yes

#1691 Forgot password email redirect to wrong URL
  src/foam/nanos/auth/resetPassword/ResetPasswordTokenService.js
Labels: cla: yes

#1690 Fix the null pointer exception when user doesn't login
  src/foam/nanos/notification/email/SMTPEmailService.js
Labels: cla: yes

#1694 referenceView update
  src/foam/u2/view/ReferenceView.js
Labels: cla: yes

#1695 Took out css in TreeView alt view that was breaking our DBTransactionsView
  src/foam/nanos/menu/TreeAltView.js
  src/foam/u2/view/TreeView.js
Labels: cla: yes

#1697 Dashboard and Card styling
  src/foam/dashboard/view/Card.js
  src/foam/u2/view/TreeView.js
Labels: cla: yes

#1698 tree view default selection as first element
  src/foam/u2/view/TreeView.js
Labels: cla: yes

#1578 Transformed Java XML into an Outputter class
  src/foam/core/AbstractArrayPropertyInfo.java
  src/foam/core/AbstractDAOPropertyPropertyInfo.java
  src/foam/core/AbstractEnumPropertyInfo.java
  src/foam/core/AbstractFObjectArrayPropertyInfo.java
  src/foam/core/AbstractFObjectPropertyInfo.java
  src/foam/core/AbstractFObjectRelationshipPropertyInfo.java
  src/foam/core/AbstractObjectPropertyInfo.java
  src/foam/core/AbstractPropertyInfo.java
  src/foam/core/PropertyInfo.java
  src/foam/core/XML.js
  src/foam/core/XMLSupport.java
  src/foam/dao/HTTPSink.java
  src/foam/dao/XMLDAO.java
  src/foam/lib/json/OutputJSON.js
  src/foam/lib/json/Outputter.java
  src/foam/lib/xml/OutputXML.js
  src/foam/lib/xml/Outputter.java
  src/foam/nanos/dig/DigWebAgent.java
  tools/classes.js
Labels: cla: yes

#1701 Added loginEnabled flag
  src/foam/nanos/auth/User.js
  src/foam/nanos/auth/UserAndGroupAuthService.java
Labels: cla: yes

#1700 Update auth service to work with user subclasses
  src/foam/nanos/auth/UserAndGroupAuthService.java
Labels: cla: yes

#1662 Do_not_merge Client login auth service
  src/files.js
  src/foam/box/AuthServiceClientBox.js
  src/foam/nanos/auth/ClientLoginAuthService.js
  src/foam/nanos/nanos.js
  src/services
  tools/classes.js
Labels: cla: yes

#1707 fix nspecfactory race condition
  src/foam/nanos/boot/NSpecFactory.java
Labels: cla: yes

#1703 Dig post request
  src/foam/nanos/dig/DIG.js
Labels: cla: yes

#1708 Replace test for session context with userId
  src/foam/nanos/http/AuthWebAgent.java
Labels: cla: yes

#1709 Add editColumnsEnabled to ScrollTableView interface
  src/foam/u2/view/ScrollTableView.js
Labels: cla: yes, enhancement

#1710 allow updating user when user is the agent
  src/foam/nanos/auth/AuthenticatedUserDAO.java
Labels: cla: yes

#1713 Remove need for userSubclassDAO in foam auth
  src/foam/nanos/auth/UserAndGroupAuthService.java
Labels: cla: yes

#1711 get the most updated agent
  src/foam/nanos/auth/AgentUserAuthService.java
Labels: cla: yes

#1715 allowing preselected Tabs in the Unstyled Tabs
  src/foam/u2/UnstyledTabs.js
Labels: cla: yes

#1717 Local Group DAO
  src/foam/dao/AuthenticatedDAOTest.java
  src/foam/nanos/auth/UserAndGroupAuthService.java
  src/services
Labels: cla: yes

#1718 Polymorphic authorization
  src/files.js
  src/foam/dao/AuthorizationSink.java
  src/foam/dao/tests.jrl
  src/foam/java/Authorizable.js
  src/foam/nanos/auth/AuthenticatedUserDAO.java
  src/foam/nanos/auth/AuthorizableAuthorizer.java
  src/foam/nanos/auth/AuthorizationDAO.java
  src/foam/nanos/auth/Authorizer.java
  src/foam/nanos/auth/User.js
  src/foam/nanos/auth/UserAuthorizationTest.java
  src/foam/nanos/auth/tests.jrl
  src/services
Labels: cla: yes

#1721 Don't show configure button if not served
  src/foam/nanos/boot/NSpec.js
Labels: cla: yes

#1720 Improve Group.isDescendantOf() method
  src/foam/nanos/auth/Group.js
Labels: cla: yes
